version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
  flutter: circleci/flutter@1.1.0
executors:
  mac-executor:
    macos:
      xcode: 14.0
    resource_class: large
jobs:
  build:
    executor: mac-executor
    steps:
    - checkout
    - flutter/install_sdk_and_pub
    - run: flutter --version
    - run:
        name: Set up environment
        command: |
          echo 'export PATH=$HOME/.pub-cache/bin:$PATH' >> $BASH_ENV
          source $BASH_ENV
    - run:
        name: Setup melos
        command: |
          flutter pub global activate melos
          melos --version
          melos bootstrap
    - run:
        name: Run Test Suite
        command: melos run test
    - run:
        name: Generate Coverage Report
        command: melos run gen_coverage
    - codecov/upload:
        file: coverage_report/lcov.info
