version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
executors:
  default-executor:
    docker:
      - image: sub6resources/flutter-melos:1.0.1
    resource_class: large
    shell: /bin/bash
jobs:
  build:
    executor: default-executor
    steps:
    - checkout
    - run: flutter --version
    - run:
        name: Setup melos
        command: |
          melos --version
          melos bootstrap
    - run:
        name: Run Test Suite
        command: melos run test
    - run:
        name: Generate Coverage Report
        command: melos run gen_coverage
    - codecov/upload:
        file: coverage_report/lcov.info
